""" Stuff """

cc_library(
    name = "pthread",
    linkopts = ["-pthread"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "libssh",
    linkopts = [
        "-L/usr/lib/x86_64-linux-gnu",
        "-lssh",
    ],
    visibility = ["//visibility:public"],
)
